// Generated by CoffeeScript 1.9.1
(function() {
  var btnIndPres, btnIndicadores, btnMesPres, btnMeses, creaLoad, ind, mes;

  btnMeses = $(".meses");

  btnIndicadores = $(".ind");

  ind = 0;

  mes = 0;

  $(function() {
    btnMeses.click(btnMesPres);
    return btnIndicadores.click(btnIndPres);
  });

  btnMesPres = function() {
    btnMeses.removeClass("active");
    $(this).addClass("active");
    mes = $(this).data("nombre");
    if (ind !== 0) {
      creaLoad();
      return $("#resultado").load("../ind_res/" + ind + "/" + mes + "/2015");
    }
  };

  btnIndPres = function() {
    btnIndicadores.removeClass("active");
    $(this).addClass("active");
    ind = $(this).data("nombre");
    if (mes !== 0) {
      creaLoad();
      return $("#resultado").load("../ind_res/" + ind + "/" + mes + "/2015");
    }
  };

  creaLoad = function() {
    $(".resultado").remove();
    return $("#resultado").append('<div class="text-center alert-info"><img src="../../img/loading.gif" class="" alt="Cargando"><h1>Cargando...</h1></div>');
  };


  /*
  btnJurPres = () ->
  	btnJuris.removeClass "active"
  	$(@).addClass "active"
  	jur = $(@).data "nombre"
  	if ind isnt 0 and mes isnt 0
  		$("#resultado").load "../ind_res/"+ind+"/"+jur+"/"+mes+"/2014"
   */

}).call(this);
